### ISSUE TITLE
Noise removal in Raman spectra

### ISSUE THREAD

**Issue by AagamShah97** [nanoMFG/GSA-Raman#112]
Reduce noise in Raman spectra to improve the signal to noise ratio and in turn, the accuracy of the Raman anaysis

https://doi.org/10.1039/C8AY01089G

https://doi.org/10.1002/jrs.1747

https://arxiv.org/abs/2009.04067

**Comment by mitishasurana** [comment]
Issue 2: Remove copper background from spectra before identification of graphene peaks
