### ISSUE TITLE
Plots don't autosize to fit in the space given

### ISSUE THREAD

**Issue by mgrober2** [nanoMFG/GSA-Raman#23]
#### Summary
Plots don't fit nicely into the window in notebook mode like they did in inline mode.
#### Expected Behavior
(...quick detail, screenshot/image maybe).
#### Actual Behavior
(.. same)
#### More Detail
- Jupyter Notebook nanoHUB Dashboard environment.
- What plotting library?
- Code filenames+line numbers are good.
- anything else?
#### Steps to Reproduce
What is the exact trigger?

**Comment by dadamsncsa** [comment]
Is this still an issue?
