### ISSUE TITLE
Create Tool Definition and webpage on nanoHUB

### ISSUE THREAD

**Issue by dadamsncsa** [nanoMFG/GSA-Raman#26]
Note: This is a duplicate of #14

Visit: https://nanohub.org/tools/create

to complete and submit form for new tool creation.

* Decide on "short name" for tool project.
* Use a version name to match planned Github release.  
  - Names like 1.0 or 0.1 are okay.  
  - If the code is considered to have untested features, use version names like (0.1-beta).
* Enter the github URL, only if the repository is public.
  - Enter the release URL rather than the master.  See [this](https://help.github.com/articles/linking-to-releases/) github doc.

#### Tool Access:
For pre-releases, use "Restricted to Groups", otherwise use "Anyone can run tool".
#### Source Code Access
Select Closed or Open, for Open source project, make sure License,  Copyright and Authors information is in place.
#### Project Area Access
Probably best to keep this "Closed" unless there is a good reason not to.
Add team collaborators nanoHUB usernames.

**Comment by mgrober2** [comment]
tool page created, will continue to work on polishing it
