### ISSUE TITLE
Browse Graphene Recipie Database

### ISSUE THREAD

**Issue by dadamsncsa** [nanoMFG/GSA-Raman#32]
### 'As a' template

    As a < (type of) user>
    I want <some software feature>
    So that <something of value can happen>

### 'In order' templates

    In order to <achive some objective>,
    for <a particular (set of) users(s)>
    we will <some new system feature>    

    In order to <achieve some scientific goal>,
    As a <type of user>
    I want <some new feature>;
    Whereas <what we are doing now>.
    
### User needs

    User [x] needs to [y] so that they can [z]

**Comment by mgrober2** [comment]
can we move this to the query repo? @dadamsncsa

**Comment by dadamsncsa** [comment]
This was a place holder, and now we don't need it...
