### ISSUE TITLE
tool in nanoHUB behaves like jupyter notebook

### ISSUE THREAD

**Issue by mgrober2** [nanoMFG/GSA-Raman#35]
The test version of the tool launches like a jupyter notebook:

![image](https://user-images.githubusercontent.com/35735694/39951800-0a04a8ca-5553-11e8-816a-99990afaeb7d.png)

**Comment by dadamsncsa** [comment]
I think this is related to the tool-mode issue we looked at last week.  Here are Josh's notes:

https://github.com/nanoMFG/DevTeam/wiki/Jupyter-Notebook-Tips-&-Tricks

the docs for this are in  section 6 here:
https://proxy.nanohub.org/weber/1309977/PLU6yzwURfS2Z7r3/64/notebooks/DOCS_AND_EXAMPLES/manual/publishing.ipynb

the problem I have is I cannot find those commands, the are not in my path.

@joshmstout: Matt and I are trying to figure out "tool mode".  The missing piece seems to be the commands:

`jupyter_tool.py`
and
`jupyter`

neither of these seem to be in our terminal.  Did you have to enable them somehow?

**Comment by joshmstout** [comment]
I don't recall having to enable anything. Are you running from the workspace terminal or the Jupyter notebooks terminal? I have only tried to run it from the Jupyter notebook terminal.

The Jupyter terminal can be opened as described at the bottom of the tips & tricks page.

**Comment by mgrober2** [comment]
I'm launching it from the nanohub tool site. Are you saying this needs to be implemented in the terminal before nanoHUB installs it?

**Comment by mgrober2** [comment]
got tool mode working locally, makes for some new issues, though
