### ISSUE TITLE
Unable to switch files in single session

### ISSUE THREAD

**Issue by kevcruse96** [nanoMFG/GSA-Raman#47]
Tool runs normally once first file is selected and fitting progresses. After fitting is complete, tool seems to break when trying to select a new file mid-session. This slows down workflow as users need to exit tool and open new session to fit multiple raman files.

**Comment by mgrober2** [comment]
nanoHub updated widgets; I've fixed the issues on my local copy, but need to check what changes were made on the svn version

**Comment by mgrober2** [comment]
It works fine; it's just resetting the button interface so you don't see the current filename, but it's keeping them all stashed
