### ISSUE TITLE
Intensity of the fitting is greater than 1

### ISSUE THREAD

**Issue by mitishasurana** [nanoMFG/GSA-Raman#91]
![image.png](https://images.zenhubusercontent.com/5e536482f56345cbe04d9cb0/8fb4dd7f-ceb9-4952-a5a8-599491534d13) 

The file:
[https://app.zenhub.com/files/118830459/34f53f0d-8839-4ef4-8447-a49a59d09a95/download](https://app.zenhub.com/files/118830459/34f53f0d-8839-4ef4-8447-a49a59d09a95/download)

**Comment by AagamShah97** [comment]
This isn't a bug. Only the uploaded spectrum is normalised. The fitted spectrum is fit around the normalised peaks. It can be slightly higher than 1.
